package com.anytypeio.anytype.data.auth.exception

/**
 * This exception is thrown when there is no changes to undo or redo.
 */
class UndoRedoExhaustedException : RuntimeException()